### ISSUE TITLE
Text to Code generation for different language

### ISSUE THREAD

**Issue by Mars-204** [salesforce/CodeT5#136]
How and where to specify the language for code generation from text input? I am trying to generate a C language code from text inputs.

**Comment by yuewang-cuhk** [comment]
Hi, for the use case of text-to-code generation, we suggest finetuning our models instead of using in a zero-shot manner.

**Comment by GaneshN29** [comment]
Hey,
How to test some input for text to code and get a output using script.
I want use Your finetuned_model

**Comment by SBhat2615** [comment]
@yuewang-cuhk want to know more about your data generation process, to finetune codet5 for text-to-code task. Where can we get that information?

**Comment by yuewang-cuhk** [comment]
你好，你的邮件我已收到，我会尽快查看~~~

**Comment by SBhat2615** [comment]
@yuewang-cuhk I'm trying to finetune the concode task using 'code' as both input & output, instead of 'nl' & 'code'. I wanted to know if we can directly use the concode finetuned checkpoints of concode task along with same tokenizers and embedding sequences.

Also, should the necessary changes be done here to load concode model instead of the base codet5 model ??
parser.add_argument("--model_tag", type=str, default='codet5_base',
                        choices=['roberta', 'codebert', 'bart_base', 'codet5_small', 'codet5_base', 'codet5_large']).
