### ISSUE TITLE
Fined-tuned checkpoints -> Code clone detection

### ISSUE THREAD

**Issue by Chinmayrane16** [salesforce/CodeT5#55]
Hi,

I am hoping to reproduce the results on code clone detection task. 
This might seem like a silly question but the fined-tuned checkpoints released doesn't include the [RobertaClassificationHead](https://github.com/salesforce/CodeT5/blob/5b37c34f4bbbfcfd972c24a9dd1f45716568ecb5/models.py#L68) parameters, right?
I am able to load only the T5ForConditionalGeneration model using the provided checkpoints for the task.

So, how do I go about loading the entire [CloneModel](https://github.com/salesforce/CodeT5/blob/5b37c34f4bbbfcfd972c24a9dd1f45716568ecb5/models.py#L62)?

**Comment by yuewang-cuhk** [comment]
Hi, thanks for pointing out this. We will update this finetuned checkpoint with the [RobertaClassificationHead](https://github.com/salesforce/CodeT5/blob/5b37c34f4bbbfcfd972c24a9dd1f45716568ecb5/models.py#L68) parameters.

**Comment by sethun** [comment]
Hi!

Not sure if it is too-early, I downloaded the latest checkpoint (Uploaded an hour ago). Seems there is some-mismatch between ClonedModel's shape and checkpoint's shape

`RuntimeError: Error(s) in loading state_dict for CloneModel:
        size mismatch for encoder.shared.weight: copying a param with shape torch.Size([32000, 768]) from checkpoint, the shape in current model is torch.Size([32100, 768]).
        size mismatch for encoder.encoder.embed_tokens.weight: copying a param with shape torch.Size([32000, 768]) from checkpoint, the shape in current model is torch.Size([32100, 768]).
        size mismatch for encoder.decoder.embed_tokens.weight: copying a param with shape torch.Size([32000, 768]) from checkpoint, the shape in current model is torch.Size([32100, 768]).
        size mismatch for encoder.lm_head.weight: copying a param with shape torch.Size([32000, 768]) from checkpoint, the shape in current model is torch.Size([32100, 768]).
`

**Comment by yuewang-cuhk** [comment]
Hi, we just updated this finetuned checkpoint yesterday. You can resolve this via adding this [line](https://github.com/salesforce/CodeT5/blob/afcc8efd4accc0a44998f9c400332579be819773/run_clone.py#L141). Following the instructions [here](https://github.com/salesforce/CodeT5#how-to-reproduce-the-results-using-the-released-finetuned-checkpoints), you will be able to reproduce the results of: `[best-f1] test-f1: 0.9500, precision: 0.9526, recall: 0.9474`. 
This result is different from the reported one in the paper due to that we report micro-f1 instead of macro-f1 following [GraphCodeBERT](https://github.com/microsoft/CodeBERT/tree/master/GraphCodeBERT/clonedetection).
